general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'   # to avoid having to press a key twice to turn on the display.
}

# Set brightness to minimum after 10 minutes
listener {
    timeout = 600                                
    on-timeout = brightnessctl -s set 10         
    on-resume = brightnessctl -r                 
}

# Lock and turn screen off after 15 minutes
listener {
    timeout = 900                                
    on-timeout = hyprlock
}

listener {
    timeout = 910
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' 
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r 
}

listener {
    timeout = 10                                                     
    on-timeout = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' 
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r 
}

